services:
  - type: web
    name: bunny-teacher-backend
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: BUNNY_STREAM_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
  - type: web
    name: bunny-teacher-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && python -m uvicorn main:app --host 0.0.0.0 --port 8000
    autoDeploy: true
    healthCheckPath: /
    plan: free
    envVars:
      - key: BUNNY_STREAM_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false